// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/testdata.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main test data structure
type TestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primitives    *PrimitiveTypes        `protobuf:"bytes,1,opt,name=primitives,proto3" json:"primitives,omitempty"`
	Collections   *CollectionTypes       `protobuf:"bytes,2,opt,name=collections,proto3" json:"collections,omitempty"`
	Complex       *ComplexTypes          `protobuf:"bytes,3,opt,name=complex,proto3" json:"complex,omitempty"`
	EdgeCases     *EdgeCaseTypes         `protobuf:"bytes,4,opt,name=edge_cases,json=edgeCases,proto3" json:"edge_cases,omitempty"`
	RealWorld     *RealWorldTypes        `protobuf:"bytes,5,opt,name=real_world,json=realWorld,proto3" json:"real_world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestData) Reset() {
	*x = TestData{}
	mi := &file_proto_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestData) ProtoMessage() {}

func (x *TestData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestData.ProtoReflect.Descriptor instead.
func (*TestData) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *TestData) GetPrimitives() *PrimitiveTypes {
	if x != nil {
		return x.Primitives
	}
	return nil
}

func (x *TestData) GetCollections() *CollectionTypes {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *TestData) GetComplex() *ComplexTypes {
	if x != nil {
		return x.Complex
	}
	return nil
}

func (x *TestData) GetEdgeCases() *EdgeCaseTypes {
	if x != nil {
		return x.EdgeCases
	}
	return nil
}

func (x *TestData) GetRealWorld() *RealWorldTypes {
	if x != nil {
		return x.RealWorld
	}
	return nil
}

// Primitive data types
type PrimitiveTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UInt8         uint32                 `protobuf:"varint,1,opt,name=u_int8,json=uInt8,proto3" json:"u_int8,omitempty"`    // uint8 -> uint32 (protobuf has no uint8)
	UInt16        uint32                 `protobuf:"varint,2,opt,name=u_int16,json=uInt16,proto3" json:"u_int16,omitempty"` // uint16 -> uint32
	UInt32        uint32                 `protobuf:"varint,3,opt,name=u_int32,json=uInt32,proto3" json:"u_int32,omitempty"`
	UInt64        uint64                 `protobuf:"varint,4,opt,name=u_int64,json=uInt64,proto3" json:"u_int64,omitempty"`
	Int8          int32                  `protobuf:"varint,5,opt,name=int8,proto3" json:"int8,omitempty"`   // int8 -> int32 (protobuf has no int8)
	Int16         int32                  `protobuf:"varint,6,opt,name=int16,proto3" json:"int16,omitempty"` // int16 -> int32
	Int32         int32                  `protobuf:"varint,7,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64         int64                  `protobuf:"varint,8,opt,name=int64,proto3" json:"int64,omitempty"`
	Float32       float32                `protobuf:"fixed32,9,opt,name=float32,proto3" json:"float32,omitempty"`
	Float64       float64                `protobuf:"fixed64,10,opt,name=float64,proto3" json:"float64,omitempty"`
	Bool          bool                   `protobuf:"varint,11,opt,name=bool,proto3" json:"bool,omitempty"`
	String_       string                 `protobuf:"bytes,12,opt,name=string,proto3" json:"string,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,13,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimitiveTypes) Reset() {
	*x = PrimitiveTypes{}
	mi := &file_proto_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimitiveTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveTypes) ProtoMessage() {}

func (x *PrimitiveTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveTypes.ProtoReflect.Descriptor instead.
func (*PrimitiveTypes) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *PrimitiveTypes) GetUInt8() uint32 {
	if x != nil {
		return x.UInt8
	}
	return 0
}

func (x *PrimitiveTypes) GetUInt16() uint32 {
	if x != nil {
		return x.UInt16
	}
	return 0
}

func (x *PrimitiveTypes) GetUInt32() uint32 {
	if x != nil {
		return x.UInt32
	}
	return 0
}

func (x *PrimitiveTypes) GetUInt64() uint64 {
	if x != nil {
		return x.UInt64
	}
	return 0
}

func (x *PrimitiveTypes) GetInt8() int32 {
	if x != nil {
		return x.Int8
	}
	return 0
}

func (x *PrimitiveTypes) GetInt16() int32 {
	if x != nil {
		return x.Int16
	}
	return 0
}

func (x *PrimitiveTypes) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *PrimitiveTypes) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *PrimitiveTypes) GetFloat32() float32 {
	if x != nil {
		return x.Float32
	}
	return 0
}

func (x *PrimitiveTypes) GetFloat64() float64 {
	if x != nil {
		return x.Float64
	}
	return 0
}

func (x *PrimitiveTypes) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *PrimitiveTypes) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *PrimitiveTypes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Collection types
type CollectionTypes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SmallIntArray    []int32                `protobuf:"varint,1,rep,packed,name=small_int_array,json=smallIntArray,proto3" json:"small_int_array,omitempty"`
	SmallStringArray []string               `protobuf:"bytes,2,rep,name=small_string_array,json=smallStringArray,proto3" json:"small_string_array,omitempty"`
	MediumIntArray   []int32                `protobuf:"varint,3,rep,packed,name=medium_int_array,json=mediumIntArray,proto3" json:"medium_int_array,omitempty"`
	MediumFloatArray []float64              `protobuf:"fixed64,4,rep,packed,name=medium_float_array,json=mediumFloatArray,proto3" json:"medium_float_array,omitempty"`
	LargeIntArray    []int64                `protobuf:"varint,5,rep,packed,name=large_int_array,json=largeIntArray,proto3" json:"large_int_array,omitempty"`
	LargeStringArray []string               `protobuf:"bytes,6,rep,name=large_string_array,json=largeStringArray,proto3" json:"large_string_array,omitempty"`
	MixedArray       []*MixedValue          `protobuf:"bytes,7,rep,name=mixed_array,json=mixedArray,proto3" json:"mixed_array,omitempty"`
	NestedIntArray   []*IntArray            `protobuf:"bytes,8,rep,name=nested_int_array,json=nestedIntArray,proto3" json:"nested_int_array,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectionTypes) Reset() {
	*x = CollectionTypes{}
	mi := &file_proto_testdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionTypes) ProtoMessage() {}

func (x *CollectionTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionTypes.ProtoReflect.Descriptor instead.
func (*CollectionTypes) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionTypes) GetSmallIntArray() []int32 {
	if x != nil {
		return x.SmallIntArray
	}
	return nil
}

func (x *CollectionTypes) GetSmallStringArray() []string {
	if x != nil {
		return x.SmallStringArray
	}
	return nil
}

func (x *CollectionTypes) GetMediumIntArray() []int32 {
	if x != nil {
		return x.MediumIntArray
	}
	return nil
}

func (x *CollectionTypes) GetMediumFloatArray() []float64 {
	if x != nil {
		return x.MediumFloatArray
	}
	return nil
}

func (x *CollectionTypes) GetLargeIntArray() []int64 {
	if x != nil {
		return x.LargeIntArray
	}
	return nil
}

func (x *CollectionTypes) GetLargeStringArray() []string {
	if x != nil {
		return x.LargeStringArray
	}
	return nil
}

func (x *CollectionTypes) GetMixedArray() []*MixedValue {
	if x != nil {
		return x.MixedArray
	}
	return nil
}

func (x *CollectionTypes) GetNestedIntArray() []*IntArray {
	if x != nil {
		return x.NestedIntArray
	}
	return nil
}

// Mixed value type using oneof
type MixedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MixedValue_IntValue
	//	*MixedValue_StringValue
	//	*MixedValue_FloatValue
	//	*MixedValue_BoolValue
	//	*MixedValue_BytesValue
	Value         isMixedValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixedValue) Reset() {
	*x = MixedValue{}
	mi := &file_proto_testdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixedValue) ProtoMessage() {}

func (x *MixedValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixedValue.ProtoReflect.Descriptor instead.
func (*MixedValue) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{3}
}

func (x *MixedValue) GetValue() isMixedValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MixedValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*MixedValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MixedValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MixedValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MixedValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MixedValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *MixedValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MixedValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MixedValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*MixedValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isMixedValue_Value interface {
	isMixedValue_Value()
}

type MixedValue_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MixedValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MixedValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type MixedValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MixedValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*MixedValue_IntValue) isMixedValue_Value() {}

func (*MixedValue_StringValue) isMixedValue_Value() {}

func (*MixedValue_FloatValue) isMixedValue_Value() {}

func (*MixedValue_BoolValue) isMixedValue_Value() {}

func (*MixedValue_BytesValue) isMixedValue_Value() {}

// Helper for nested arrays
type IntArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntArray) Reset() {
	*x = IntArray{}
	mi := &file_proto_testdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArray) ProtoMessage() {}

func (x *IntArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArray.ProtoReflect.Descriptor instead.
func (*IntArray) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{4}
}

func (x *IntArray) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Complex types
type ComplexTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Company       *Company               `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	People        []*Person              `protobuf:"bytes,3,rep,name=people,proto3" json:"people,omitempty"`
	Departments   []*Department          `protobuf:"bytes,4,rep,name=departments,proto3" json:"departments,omitempty"`
	StringMap     []*StringMapEntry      `protobuf:"bytes,5,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty"`
	IntMap        []*IntMapEntry         `protobuf:"bytes,6,rep,name=int_map,json=intMap,proto3" json:"int_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexTypes) Reset() {
	*x = ComplexTypes{}
	mi := &file_proto_testdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexTypes) ProtoMessage() {}

func (x *ComplexTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexTypes.ProtoReflect.Descriptor instead.
func (*ComplexTypes) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{5}
}

func (x *ComplexTypes) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *ComplexTypes) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *ComplexTypes) GetPeople() []*Person {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *ComplexTypes) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *ComplexTypes) GetStringMap() []*StringMapEntry {
	if x != nil {
		return x.StringMap
	}
	return nil
}

func (x *ComplexTypes) GetIntMap() []*IntMapEntry {
	if x != nil {
		return x.IntMap
	}
	return nil
}

// Map entries (protobuf map alternative)
type StringMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMapEntry) Reset() {
	*x = StringMapEntry{}
	mi := &file_proto_testdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMapEntry) ProtoMessage() {}

func (x *StringMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMapEntry.ProtoReflect.Descriptor instead.
func (*StringMapEntry) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{6}
}

func (x *StringMapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StringMapEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IntMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntMapEntry) Reset() {
	*x = IntMapEntry{}
	mi := &file_proto_testdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntMapEntry) ProtoMessage() {}

func (x *IntMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntMapEntry.ProtoReflect.Descriptor instead.
func (*IntMapEntry) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{7}
}

func (x *IntMapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IntMapEntry) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Supporting structures
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      []*StringMapEntry      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_testdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{8}
}

func (x *Person) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Person) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Person) GetMetadata() []*StringMapEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Founded       int32                  `protobuf:"varint,3,opt,name=founded,proto3" json:"founded,omitempty"`
	Employees     []*Person              `protobuf:"bytes,4,rep,name=employees,proto3" json:"employees,omitempty"`
	Departments   []*Department          `protobuf:"bytes,5,rep,name=departments,proto3" json:"departments,omitempty"`
	Revenue       float64                `protobuf:"fixed64,6,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_proto_testdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{9}
}

func (x *Company) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetFounded() int32 {
	if x != nil {
		return x.Founded
	}
	return 0
}

func (x *Company) GetEmployees() []*Person {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *Company) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *Company) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Manager       *Person                `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
	Budget        float64                `protobuf:"fixed64,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Projects      []string               `protobuf:"bytes,5,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_proto_testdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{10}
}

func (x *Department) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetManager() *Person {
	if x != nil {
		return x.Manager
	}
	return nil
}

func (x *Department) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *Department) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

// Edge cases
type EdgeCaseTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmptyString   string                 `protobuf:"bytes,1,opt,name=empty_string,json=emptyString,proto3" json:"empty_string,omitempty"`
	EmptyBytes    []byte                 `protobuf:"bytes,2,opt,name=empty_bytes,json=emptyBytes,proto3" json:"empty_bytes,omitempty"`
	EmptyArray    []int32                `protobuf:"varint,3,rep,packed,name=empty_array,json=emptyArray,proto3" json:"empty_array,omitempty"`
	NilBytes      []byte                 `protobuf:"bytes,4,opt,name=nil_bytes,json=nilBytes,proto3" json:"nil_bytes,omitempty"`
	LargeString   string                 `protobuf:"bytes,5,opt,name=large_string,json=largeString,proto3" json:"large_string,omitempty"`
	LargeBytes    []byte                 `protobuf:"bytes,6,opt,name=large_bytes,json=largeBytes,proto3" json:"large_bytes,omitempty"`
	UnicodeString string                 `protobuf:"bytes,7,opt,name=unicode_string,json=unicodeString,proto3" json:"unicode_string,omitempty"`
	SpecialChars  string                 `protobuf:"bytes,8,opt,name=special_chars,json=specialChars,proto3" json:"special_chars,omitempty"`
	MaxInt64      int64                  `protobuf:"varint,9,opt,name=max_int64,json=maxInt64,proto3" json:"max_int64,omitempty"`
	MinInt64      int64                  `protobuf:"varint,10,opt,name=min_int64,json=minInt64,proto3" json:"min_int64,omitempty"`
	MaxUint64     uint64                 `protobuf:"varint,11,opt,name=max_uint64,json=maxUint64,proto3" json:"max_uint64,omitempty"`
	SmallFloat    float64                `protobuf:"fixed64,12,opt,name=small_float,json=smallFloat,proto3" json:"small_float,omitempty"`
	LargeFloat    float64                `protobuf:"fixed64,13,opt,name=large_float,json=largeFloat,proto3" json:"large_float,omitempty"`
	NanFloat      float64                `protobuf:"fixed64,14,opt,name=nan_float,json=nanFloat,proto3" json:"nan_float,omitempty"`
	InfFloat      float64                `protobuf:"fixed64,15,opt,name=inf_float,json=infFloat,proto3" json:"inf_float,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeCaseTypes) Reset() {
	*x = EdgeCaseTypes{}
	mi := &file_proto_testdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeCaseTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeCaseTypes) ProtoMessage() {}

func (x *EdgeCaseTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeCaseTypes.ProtoReflect.Descriptor instead.
func (*EdgeCaseTypes) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{11}
}

func (x *EdgeCaseTypes) GetEmptyString() string {
	if x != nil {
		return x.EmptyString
	}
	return ""
}

func (x *EdgeCaseTypes) GetEmptyBytes() []byte {
	if x != nil {
		return x.EmptyBytes
	}
	return nil
}

func (x *EdgeCaseTypes) GetEmptyArray() []int32 {
	if x != nil {
		return x.EmptyArray
	}
	return nil
}

func (x *EdgeCaseTypes) GetNilBytes() []byte {
	if x != nil {
		return x.NilBytes
	}
	return nil
}

func (x *EdgeCaseTypes) GetLargeString() string {
	if x != nil {
		return x.LargeString
	}
	return ""
}

func (x *EdgeCaseTypes) GetLargeBytes() []byte {
	if x != nil {
		return x.LargeBytes
	}
	return nil
}

func (x *EdgeCaseTypes) GetUnicodeString() string {
	if x != nil {
		return x.UnicodeString
	}
	return ""
}

func (x *EdgeCaseTypes) GetSpecialChars() string {
	if x != nil {
		return x.SpecialChars
	}
	return ""
}

func (x *EdgeCaseTypes) GetMaxInt64() int64 {
	if x != nil {
		return x.MaxInt64
	}
	return 0
}

func (x *EdgeCaseTypes) GetMinInt64() int64 {
	if x != nil {
		return x.MinInt64
	}
	return 0
}

func (x *EdgeCaseTypes) GetMaxUint64() uint64 {
	if x != nil {
		return x.MaxUint64
	}
	return 0
}

func (x *EdgeCaseTypes) GetSmallFloat() float64 {
	if x != nil {
		return x.SmallFloat
	}
	return 0
}

func (x *EdgeCaseTypes) GetLargeFloat() float64 {
	if x != nil {
		return x.LargeFloat
	}
	return 0
}

func (x *EdgeCaseTypes) GetNanFloat() float64 {
	if x != nil {
		return x.NanFloat
	}
	return 0
}

func (x *EdgeCaseTypes) GetInfFloat() float64 {
	if x != nil {
		return x.InfFloat
	}
	return 0
}

// Real world types
type RealWorldTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProfile   *UserProfile           `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	Config        *Configuration         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	TimeSeries    []*TimeSeriesPoint     `protobuf:"bytes,3,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,4,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	ApiResponse   *APIResponse           `protobuf:"bytes,5,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealWorldTypes) Reset() {
	*x = RealWorldTypes{}
	mi := &file_proto_testdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealWorldTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealWorldTypes) ProtoMessage() {}

func (x *RealWorldTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealWorldTypes.ProtoReflect.Descriptor instead.
func (*RealWorldTypes) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{12}
}

func (x *RealWorldTypes) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *RealWorldTypes) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RealWorldTypes) GetTimeSeries() []*TimeSeriesPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

func (x *RealWorldTypes) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *RealWorldTypes) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	BirthDate     int64                  `protobuf:"varint,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // Unix timestamp
	Preferences   []*MixedMapEntry       `protobuf:"bytes,7,rep,name=preferences,proto3" json:"preferences,omitempty"`
	Friends       []uint64               `protobuf:"varint,8,rep,packed,name=friends,proto3" json:"friends,omitempty"`
	Groups        []string               `protobuf:"bytes,9,rep,name=groups,proto3" json:"groups,omitempty"`
	LastLogin     int64                  `protobuf:"varint,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"` // Unix timestamp
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ProfilePic    []byte                 `protobuf:"bytes,12,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_testdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{13}
}

func (x *UserProfile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserProfile) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

func (x *UserProfile) GetPreferences() []*MixedMapEntry {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UserProfile) GetFriends() []uint64 {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *UserProfile) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserProfile) GetLastLogin() int64 {
	if x != nil {
		return x.LastLogin
	}
	return 0
}

func (x *UserProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserProfile) GetProfilePic() []byte {
	if x != nil {
		return x.ProfilePic
	}
	return nil
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Features      []*BoolMapEntry        `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	Limits        []*IntMapEntry         `protobuf:"bytes,5,rep,name=limits,proto3" json:"limits,omitempty"`
	Endpoints     []string               `protobuf:"bytes,6,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Timeouts      []*IntMapEntry         `protobuf:"bytes,7,rep,name=timeouts,proto3" json:"timeouts,omitempty"`
	Debug         bool                   `protobuf:"varint,8,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_testdata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{14}
}

func (x *Configuration) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Configuration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Configuration) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Configuration) GetFeatures() []*BoolMapEntry {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Configuration) GetLimits() []*IntMapEntry {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Configuration) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Configuration) GetTimeouts() []*IntMapEntry {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

func (x *Configuration) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Tags          []*StringMapEntry      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_proto_testdata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{15}
}

func (x *TimeSeriesPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TimeSeriesPoint) GetTags() []*StringMapEntry {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TimeSeriesPoint) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ThreadId      uint32                 `protobuf:"varint,5,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Data          []*MixedMapEntry       `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_testdata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{16}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetThreadId() uint32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *LogEntry) GetData() []*MixedMapEntry {
	if x != nil {
		return x.Data
	}
	return nil
}

type APIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MixedValue            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Errors        []string               `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	Meta          []*MixedMapEntry       `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_proto_testdata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{17}
}

func (x *APIResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *APIResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIResponse) GetData() *MixedValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *APIResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *APIResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *APIResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *APIResponse) GetMeta() []*MixedMapEntry {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Map entry types for different value types
type BoolMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolMapEntry) Reset() {
	*x = BoolMapEntry{}
	mi := &file_proto_testdata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMapEntry) ProtoMessage() {}

func (x *BoolMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMapEntry.ProtoReflect.Descriptor instead.
func (*BoolMapEntry) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{18}
}

func (x *BoolMapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BoolMapEntry) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type MixedMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *MixedValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixedMapEntry) Reset() {
	*x = MixedMapEntry{}
	mi := &file_proto_testdata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixedMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixedMapEntry) ProtoMessage() {}

func (x *MixedMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testdata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixedMapEntry.ProtoReflect.Descriptor instead.
func (*MixedMapEntry) Descriptor() ([]byte, []int) {
	return file_proto_testdata_proto_rawDescGZIP(), []int{19}
}

func (x *MixedMapEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MixedMapEntry) GetValue() *MixedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_testdata_proto protoreflect.FileDescriptor

const file_proto_testdata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/testdata.proto\x12\btestdata\"\xa4\x02\n" +
	"\bTestData\x128\n" +
	"\n" +
	"primitives\x18\x01 \x01(\v2\x18.testdata.PrimitiveTypesR\n" +
	"primitives\x12;\n" +
	"\vcollections\x18\x02 \x01(\v2\x19.testdata.CollectionTypesR\vcollections\x120\n" +
	"\acomplex\x18\x03 \x01(\v2\x16.testdata.ComplexTypesR\acomplex\x126\n" +
	"\n" +
	"edge_cases\x18\x04 \x01(\v2\x17.testdata.EdgeCaseTypesR\tedgeCases\x127\n" +
	"\n" +
	"real_world\x18\x05 \x01(\v2\x18.testdata.RealWorldTypesR\trealWorld\"\xbe\x02\n" +
	"\x0ePrimitiveTypes\x12\x15\n" +
	"\x06u_int8\x18\x01 \x01(\rR\x05uInt8\x12\x17\n" +
	"\au_int16\x18\x02 \x01(\rR\x06uInt16\x12\x17\n" +
	"\au_int32\x18\x03 \x01(\rR\x06uInt32\x12\x17\n" +
	"\au_int64\x18\x04 \x01(\x04R\x06uInt64\x12\x12\n" +
	"\x04int8\x18\x05 \x01(\x05R\x04int8\x12\x14\n" +
	"\x05int16\x18\x06 \x01(\x05R\x05int16\x12\x14\n" +
	"\x05int32\x18\a \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\b \x01(\x03R\x05int64\x12\x18\n" +
	"\afloat32\x18\t \x01(\x02R\afloat32\x12\x18\n" +
	"\afloat64\x18\n" +
	" \x01(\x01R\afloat64\x12\x12\n" +
	"\x04bool\x18\v \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\f \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\r \x01(\fR\x05bytes\"\x8a\x03\n" +
	"\x0fCollectionTypes\x12&\n" +
	"\x0fsmall_int_array\x18\x01 \x03(\x05R\rsmallIntArray\x12,\n" +
	"\x12small_string_array\x18\x02 \x03(\tR\x10smallStringArray\x12(\n" +
	"\x10medium_int_array\x18\x03 \x03(\x05R\x0emediumIntArray\x12,\n" +
	"\x12medium_float_array\x18\x04 \x03(\x01R\x10mediumFloatArray\x12&\n" +
	"\x0flarge_int_array\x18\x05 \x03(\x03R\rlargeIntArray\x12,\n" +
	"\x12large_string_array\x18\x06 \x03(\tR\x10largeStringArray\x125\n" +
	"\vmixed_array\x18\a \x03(\v2\x14.testdata.MixedValueR\n" +
	"mixedArray\x12<\n" +
	"\x10nested_int_array\x18\b \x03(\v2\x12.testdata.IntArrayR\x0enestedIntArray\"\xc0\x01\n" +
	"\n" +
	"MixedValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\"\n" +
	"\bIntArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"\xb0\x02\n" +
	"\fComplexTypes\x12(\n" +
	"\x06person\x18\x01 \x01(\v2\x10.testdata.PersonR\x06person\x12+\n" +
	"\acompany\x18\x02 \x01(\v2\x11.testdata.CompanyR\acompany\x12(\n" +
	"\x06people\x18\x03 \x03(\v2\x10.testdata.PersonR\x06people\x126\n" +
	"\vdepartments\x18\x04 \x03(\v2\x14.testdata.DepartmentR\vdepartments\x127\n" +
	"\n" +
	"string_map\x18\x05 \x03(\v2\x18.testdata.StringMapEntryR\tstringMap\x12.\n" +
	"\aint_map\x18\x06 \x03(\v2\x15.testdata.IntMapEntryR\x06intMap\"8\n" +
	"\x0eStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"5\n" +
	"\vIntMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\xb6\x01\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x124\n" +
	"\bmetadata\x18\a \x03(\v2\x18.testdata.StringMapEntryR\bmetadata\"\xc9\x01\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\afounded\x18\x03 \x01(\x05R\afounded\x12.\n" +
	"\temployees\x18\x04 \x03(\v2\x10.testdata.PersonR\temployees\x126\n" +
	"\vdepartments\x18\x05 \x03(\v2\x14.testdata.DepartmentR\vdepartments\x12\x18\n" +
	"\arevenue\x18\x06 \x01(\x01R\arevenue\"\x90\x01\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\amanager\x18\x03 \x01(\v2\x10.testdata.PersonR\amanager\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x01R\x06budget\x12\x1a\n" +
	"\bprojects\x18\x05 \x03(\tR\bprojects\"\xf6\x03\n" +
	"\rEdgeCaseTypes\x12!\n" +
	"\fempty_string\x18\x01 \x01(\tR\vemptyString\x12\x1f\n" +
	"\vempty_bytes\x18\x02 \x01(\fR\n" +
	"emptyBytes\x12\x1f\n" +
	"\vempty_array\x18\x03 \x03(\x05R\n" +
	"emptyArray\x12\x1b\n" +
	"\tnil_bytes\x18\x04 \x01(\fR\bnilBytes\x12!\n" +
	"\flarge_string\x18\x05 \x01(\tR\vlargeString\x12\x1f\n" +
	"\vlarge_bytes\x18\x06 \x01(\fR\n" +
	"largeBytes\x12%\n" +
	"\x0eunicode_string\x18\a \x01(\tR\runicodeString\x12#\n" +
	"\rspecial_chars\x18\b \x01(\tR\fspecialChars\x12\x1b\n" +
	"\tmax_int64\x18\t \x01(\x03R\bmaxInt64\x12\x1b\n" +
	"\tmin_int64\x18\n" +
	" \x01(\x03R\bminInt64\x12\x1d\n" +
	"\n" +
	"max_uint64\x18\v \x01(\x04R\tmaxUint64\x12\x1f\n" +
	"\vsmall_float\x18\f \x01(\x01R\n" +
	"smallFloat\x12\x1f\n" +
	"\vlarge_float\x18\r \x01(\x01R\n" +
	"largeFloat\x12\x1b\n" +
	"\tnan_float\x18\x0e \x01(\x01R\bnanFloat\x12\x1b\n" +
	"\tinf_float\x18\x0f \x01(\x01R\binfFloat\"\xa6\x02\n" +
	"\x0eRealWorldTypes\x128\n" +
	"\fuser_profile\x18\x01 \x01(\v2\x15.testdata.UserProfileR\vuserProfile\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.testdata.ConfigurationR\x06config\x12:\n" +
	"\vtime_series\x18\x03 \x03(\v2\x19.testdata.TimeSeriesPointR\n" +
	"timeSeries\x123\n" +
	"\vlog_entries\x18\x04 \x03(\v2\x12.testdata.LogEntryR\n" +
	"logEntries\x128\n" +
	"\fapi_response\x18\x05 \x01(\v2\x15.testdata.APIResponseR\vapiResponse\"\x81\x03\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\x03R\tbirthDate\x129\n" +
	"\vpreferences\x18\a \x03(\v2\x17.testdata.MixedMapEntryR\vpreferences\x12\x18\n" +
	"\afriends\x18\b \x03(\x04R\afriends\x12\x16\n" +
	"\x06groups\x18\t \x03(\tR\x06groups\x12\x1d\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\x03R\tlastLogin\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x1f\n" +
	"\vprofile_pic\x18\f \x01(\fR\n" +
	"profilePic\"\xb0\x02\n" +
	"\rConfiguration\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x122\n" +
	"\bfeatures\x18\x04 \x03(\v2\x16.testdata.BoolMapEntryR\bfeatures\x12-\n" +
	"\x06limits\x18\x05 \x03(\v2\x15.testdata.IntMapEntryR\x06limits\x12\x1c\n" +
	"\tendpoints\x18\x06 \x03(\tR\tendpoints\x121\n" +
	"\btimeouts\x18\a \x03(\v2\x15.testdata.IntMapEntryR\btimeouts\x12\x14\n" +
	"\x05debug\x18\b \x01(\bR\x05debug\"\x8b\x01\n" +
	"\x0fTimeSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12,\n" +
	"\x04tags\x18\x03 \x03(\v2\x18.testdata.StringMapEntryR\x04tags\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\xba\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1b\n" +
	"\tthread_id\x18\x05 \x01(\rR\bthreadId\x12+\n" +
	"\x04data\x18\x06 \x03(\v2\x17.testdata.MixedMapEntryR\x04data\"\xeb\x01\n" +
	"\vAPIResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.testdata.MixedValueR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors\x12+\n" +
	"\x04meta\x18\a \x03(\v2\x17.testdata.MixedMapEntryR\x04meta\"6\n" +
	"\fBoolMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"M\n" +
	"\rMixedMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.testdata.MixedValueR\x05valueB\x14Z\x12ebe/proto/testdatab\x06proto3"

var (
	file_proto_testdata_proto_rawDescOnce sync.Once
	file_proto_testdata_proto_rawDescData []byte
)

func file_proto_testdata_proto_rawDescGZIP() []byte {
	file_proto_testdata_proto_rawDescOnce.Do(func() {
		file_proto_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_testdata_proto_rawDesc), len(file_proto_testdata_proto_rawDesc)))
	})
	return file_proto_testdata_proto_rawDescData
}

var file_proto_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_testdata_proto_goTypes = []any{
	(*TestData)(nil),        // 0: testdata.TestData
	(*PrimitiveTypes)(nil),  // 1: testdata.PrimitiveTypes
	(*CollectionTypes)(nil), // 2: testdata.CollectionTypes
	(*MixedValue)(nil),      // 3: testdata.MixedValue
	(*IntArray)(nil),        // 4: testdata.IntArray
	(*ComplexTypes)(nil),    // 5: testdata.ComplexTypes
	(*StringMapEntry)(nil),  // 6: testdata.StringMapEntry
	(*IntMapEntry)(nil),     // 7: testdata.IntMapEntry
	(*Person)(nil),          // 8: testdata.Person
	(*Company)(nil),         // 9: testdata.Company
	(*Department)(nil),      // 10: testdata.Department
	(*EdgeCaseTypes)(nil),   // 11: testdata.EdgeCaseTypes
	(*RealWorldTypes)(nil),  // 12: testdata.RealWorldTypes
	(*UserProfile)(nil),     // 13: testdata.UserProfile
	(*Configuration)(nil),   // 14: testdata.Configuration
	(*TimeSeriesPoint)(nil), // 15: testdata.TimeSeriesPoint
	(*LogEntry)(nil),        // 16: testdata.LogEntry
	(*APIResponse)(nil),     // 17: testdata.APIResponse
	(*BoolMapEntry)(nil),    // 18: testdata.BoolMapEntry
	(*MixedMapEntry)(nil),   // 19: testdata.MixedMapEntry
}
var file_proto_testdata_proto_depIdxs = []int32{
	1,  // 0: testdata.TestData.primitives:type_name -> testdata.PrimitiveTypes
	2,  // 1: testdata.TestData.collections:type_name -> testdata.CollectionTypes
	5,  // 2: testdata.TestData.complex:type_name -> testdata.ComplexTypes
	11, // 3: testdata.TestData.edge_cases:type_name -> testdata.EdgeCaseTypes
	12, // 4: testdata.TestData.real_world:type_name -> testdata.RealWorldTypes
	3,  // 5: testdata.CollectionTypes.mixed_array:type_name -> testdata.MixedValue
	4,  // 6: testdata.CollectionTypes.nested_int_array:type_name -> testdata.IntArray
	8,  // 7: testdata.ComplexTypes.person:type_name -> testdata.Person
	9,  // 8: testdata.ComplexTypes.company:type_name -> testdata.Company
	8,  // 9: testdata.ComplexTypes.people:type_name -> testdata.Person
	10, // 10: testdata.ComplexTypes.departments:type_name -> testdata.Department
	6,  // 11: testdata.ComplexTypes.string_map:type_name -> testdata.StringMapEntry
	7,  // 12: testdata.ComplexTypes.int_map:type_name -> testdata.IntMapEntry
	6,  // 13: testdata.Person.metadata:type_name -> testdata.StringMapEntry
	8,  // 14: testdata.Company.employees:type_name -> testdata.Person
	10, // 15: testdata.Company.departments:type_name -> testdata.Department
	8,  // 16: testdata.Department.manager:type_name -> testdata.Person
	13, // 17: testdata.RealWorldTypes.user_profile:type_name -> testdata.UserProfile
	14, // 18: testdata.RealWorldTypes.config:type_name -> testdata.Configuration
	15, // 19: testdata.RealWorldTypes.time_series:type_name -> testdata.TimeSeriesPoint
	16, // 20: testdata.RealWorldTypes.log_entries:type_name -> testdata.LogEntry
	17, // 21: testdata.RealWorldTypes.api_response:type_name -> testdata.APIResponse
	19, // 22: testdata.UserProfile.preferences:type_name -> testdata.MixedMapEntry
	18, // 23: testdata.Configuration.features:type_name -> testdata.BoolMapEntry
	7,  // 24: testdata.Configuration.limits:type_name -> testdata.IntMapEntry
	7,  // 25: testdata.Configuration.timeouts:type_name -> testdata.IntMapEntry
	6,  // 26: testdata.TimeSeriesPoint.tags:type_name -> testdata.StringMapEntry
	19, // 27: testdata.LogEntry.data:type_name -> testdata.MixedMapEntry
	3,  // 28: testdata.APIResponse.data:type_name -> testdata.MixedValue
	19, // 29: testdata.APIResponse.meta:type_name -> testdata.MixedMapEntry
	3,  // 30: testdata.MixedMapEntry.value:type_name -> testdata.MixedValue
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_testdata_proto_init() }
func file_proto_testdata_proto_init() {
	if File_proto_testdata_proto != nil {
		return
	}
	file_proto_testdata_proto_msgTypes[3].OneofWrappers = []any{
		(*MixedValue_IntValue)(nil),
		(*MixedValue_StringValue)(nil),
		(*MixedValue_FloatValue)(nil),
		(*MixedValue_BoolValue)(nil),
		(*MixedValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_testdata_proto_rawDesc), len(file_proto_testdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_testdata_proto_goTypes,
		DependencyIndexes: file_proto_testdata_proto_depIdxs,
		MessageInfos:      file_proto_testdata_proto_msgTypes,
	}.Build()
	File_proto_testdata_proto = out.File
	file_proto_testdata_proto_goTypes = nil
	file_proto_testdata_proto_depIdxs = nil
}
